In [80]:
import pandas as pd

In [81]:
df = pd.read_csv("C:\\Users\\jouin\\Downloads\\archive\\customers (1).csv")
df.head()

  customer_id  gender  age        city signup_date loyalty_member
0       C0001    Male   19   Liverpool  2023-10-17            Yes
1       C0002    Male   65  Manchester  2022-08-17            Yes
2       C0003  Female   20      London  2023-08-28            Yes
3       C0004    Male   50      London  2022-08-12            Yes
4       C0005  Female   32  Nottingham  2023-10-28             No

In [82]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   customer_id     1200 non-null   str
 1   gender          1200 non-null   str
 2   age             1200 non-null   int64
 3   city            1200 non-null   str
 4   signup_date     1200 non-null   str
 5   loyalty_member  1200 non-null   str
dtypes: int64(1), str(5)
memory usage: 56.4 KB

In [83]:
df.describe()

               age
count  1200.000000
mean     41.615833
std      13.719515
min      18.000000
25%      30.000000
50%      41.000000
75%      54.000000
max      65.000000

In [84]:
df["city"].value_counts()

city
Sheffield     163
Nottingham    160
Birmingham    159
Bristol       156
London        146
Leeds         146
Liverpool     137
Manchester    133
Name: count, dtype: int64

In [85]:
df_orders = pd.read_csv("C:\\Users\\jouin\\Downloads\\archive\\orders (1).csv")
df_orders.head()

  order_id customer_id product_id  order_date  quantity payment_method
0   O00001       C0692       P006  2023-01-29         4           Card
1   O00002       C1072       P059  2023-04-19         5           Card
2   O00003       C1187       P030  2024-01-15         1           Card
3   O00004       C0290       P063  2024-01-12         1           Cash
4   O00005       C0094       P032  2024-04-09         2           Card

In [86]:
df_products = pd.read_csv("C:\\Users\\jouin\\Downloads\\archive\\products (1).csv")
df_products.head()

  product_id    product_name category   price
0       P001       Blender 1   Beauty  272.76
1       P002       Perfume 2     Home  132.09
2       P003  Water Bottle 3     Home   58.58
3       P004   Smart Watch 4     Home  220.82
4       P005       Perfume 5     Home   27.81

In [87]:
df_merged = df_orders.merge(df_products, on="product_id")
df_merged.groupby("product_name")["quantity"].sum().sort_values(ascending=False)

product_name
Monitor 55              201
Wireless Mouse 60       193
Bluetooth Speaker 18    191
Face Cream 67           178
Water Bottle 71         178
                       ...
Smart Watch 8           108
Perfume 45              105
USB Cable 50            104
Hair Dryer 35            97
Blender 75               85
Name: quantity, Length: 80, dtype: int64

In [88]:
df_merged = df_orders.merge(df_products, on="product_id")
df_merged["fatturato"] = df_merged["quantity"] * df_merged["price"]
df_merged.groupby("category")["fatturato"].sum().sort_values(ascending=False)

category
Home           473002.14
Sports         403963.89
Clothing       319942.70
Beauty         239438.96
Electronics    208470.02
Name: fatturato, dtype: float64